### ISSUE TITLE
Better way to list Geofabrik content

### ISSUE THREAD

**Issue by woodpeck** [julien-noblet/download-geofabrik#232]
I note that this project contains code to iterate over Geofabrik's HTML pages to get a list of all downloadable files. You might want to investigate using the JSON index, http://download.geofabrik.de/index.json.gz - it should contain everything you need in one place and save you from having to scrape the HTML. Let me know if there's anything you need that is missing from the file.

**Comment by nyurik** [comment]
I have implemented support for the above index, as part of the OpenMapTiles's [multi-streamed data downloader](https://github.com/openmaptiles/openmaptiles-tools#multi-streamed-osm-data-downloader) (not yet merged):

Implementation - https://github.com/openmaptiles/openmaptiles-tools/pull/163/files#diff-73b9977bf9f0cdb773eb051f537d3e1fR311

@woodpeck there seems to be a few bugs/gotchas in the published data (they can be worked around, but probably better to fix in upstream):
* The `parent` field does not always match `id` field, e.g. `norcal` and `socal` parent is `california` instead of `us/california`
* The `name` field is html-encoded, whereas one would expect JSON to be in pure utf-8

Lastly, this is not published but can be deduced -- doing a `url.replace("-latest.osm.pbf", "-updates/state.txt")` produces state.txt URL.  Not sure if state.txt URL should be published or not.

**Comment by woodpeck** [comment]
I wonder if, before more people start using the index.json.gz, we should perhaps introduce a versioning (e.g. index.v01.json.gz or so) so that when we make potentially breaking changes we can support older versions at least for a while...? [sorry for hijacking this ticket but there's no git repo for the Geofabrik dowhload server where this could go instead ;)]

**Comment by nyurik** [comment]
@woodpeck sure, but if you ever decide to publish a different version of the index, just put it under a different URL, i.e.  `/index.v02.json.gz`. You can't really rename the v1 to anything else as it is already being used, right?

If you are going to modify it a bit, I would also highly recommend getting rid of the `.gz` -- there is no point to gzip any content like this -- the file is small enough, and it is the job of the transport protocol (http) to gzip things transparently.  This will make usage more straightforward, and I suspect the web server will handle the gziping/caching (e.g. Varnish would cache it gzipped, and if serving from a cloud bucket like GCP, you can also specify compression meta tags).

**Comment by woodpeck** [comment]
http://download.geofabrik.de/technical.html now has a paragraph at the bottom describing the index file. The current version of the index file is https://download.geofabrik.de/index-v1.json or, if you do not need geometries, https://download.geofabrik.de/index-v1-nogeom.json. The index.json.gz mentioned above is still supported but deprecated.

**Comment by nyurik** [comment]
Thanks @woodpeck!  I did notice a minor problem though -- your server seems to be misconfigured to not gzip json content automatically.

Also, are you planning to publish the state files as part of the `urls` list, or will this continue to be a hidden feature?  I guess adding it to the `urls` object would not be a breaking feature and can still be called v1.

Thanks for making it into a stable API!

**Comment by julien-noblet** [comment]
@woodpeck , @nyurik I've implemented it!
You can try it here https://github.com/julien-noblet/download-geofabrik/releases/tag/v2.6.0-rc1
